# Generated by Django 3.1.2 on 2020-10-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betsvolume',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
