# Generated by Django 3.1.2 on 2020-10-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20201009_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betsvolume',
            name='amount',
            field=models.CharField(max_length=30),
        ),
    ]
